Fix wrong version check in Release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -46,11 +46,9 @@ jobs:
             echo "Version in Cargo.toml (${version_in_cargo_toml}) does not match tag (${tag})"
             exit 1
           fi
-          echo "Checking major.minor version in README.md against tag ${tag}"
-          tag_version="${tag#v}"
-          major_minor=$(echo "${tag_version}" | cut -d '.' -f 1,2)
-          if ! grep -A 100 "## Dependencies" README.md | grep -q "^| ${major_minor}"; then
-            echo "Major.minor version (${major_minor}) from tag not found in README.md Dependencies table"
+          echo "Checking version in CHANGELOG.md against tag ${tag}"
+          if ! grep -q "^## \[${tag_version}\]" CHANGELOG.md; then
+            echo "Version (${tag_version}) from tag not found in CHANGELOG.md"
             exit 1
           fi
 
